// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "owned_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "display_name", Type: field.TypeString, Size: 150},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "resource", Type: field.TypeString, Size: 50},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_name",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[6]},
			},
			{
				Name:    "permission_is_active",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[10]},
			},
			{
				Name:    "permission_created_at",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[1]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "owned_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "display_name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "priority", Type: field.TypeInt, Default: 0},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[6]},
			},
			{
				Name:    "role_is_active",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[9]},
			},
			{
				Name:    "role_priority",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[10]},
			},
			{
				Name:    "role_created_at",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[1]},
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "owned_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "can_read", Type: field.TypeBool, Default: false},
		{Name: "can_create", Type: field.TypeBool, Default: false},
		{Name: "can_update", Type: field.TypeBool, Default: false},
		{Name: "can_delete", Type: field.TypeBool, Default: false},
		{Name: "role_permission_role", Type: field.TypeInt},
		{Name: "role_permission_permission", Type: field.TypeInt},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_roles_role",
				Columns:    []*schema.Column{RolePermissionsColumns[10]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_permissions_permissions_permission",
				Columns:    []*schema.Column{RolePermissionsColumns[11]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "owned_by", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "domain", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "suspended", "pending"}, Default: "pending"},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_slug",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[6]},
			},
			{
				Name:    "tenant_domain",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[7]},
			},
			{
				Name:    "tenant_status",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[9]},
			},
			{
				Name:    "tenant_is_active",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[13]},
			},
			{
				Name:    "tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "owned_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 50},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "user_type", Type: field.TypeString, Size: 50, Default: "staff"},
		{Name: "user_code", Type: field.TypeString, Unique: true, Nullable: true, Size: 20},
		{Name: "company_name", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "customer_type", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "payment_terms", Type: field.TypeInt, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_login", Type: field.TypeTime, Nullable: true},
		{Name: "user_role", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_roles_role",
				Columns:    []*schema.Column{UsersColumns[21]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PermissionsTable,
		RolesTable,
		RolePermissionsTable,
		TenantsTable,
		UsersTable,
	}
)

func init() {
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	UsersTable.ForeignKeys[0].RefTable = RolesTable
}
