// Code generated by ent, DO NOT EDIT.

package rolepermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldTenantID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedBy, v))
}

// OwnedBy applies equality check predicate on the "owned_by" field. It's identical to OwnedByEQ.
func OwnedBy(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldOwnedBy, v))
}

// CanRead applies equality check predicate on the "can_read" field. It's identical to CanReadEQ.
func CanRead(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanRead, v))
}

// CanCreate applies equality check predicate on the "can_create" field. It's identical to CanCreateEQ.
func CanCreate(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanCreate, v))
}

// CanUpdate applies equality check predicate on the "can_update" field. It's identical to CanUpdateEQ.
func CanUpdate(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanUpdate, v))
}

// CanDelete applies equality check predicate on the "can_delete" field. It's identical to CanDeleteEQ.
func CanDelete(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanDelete, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotNull(FieldTenantID))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotNull(FieldCreatedBy))
}

// OwnedByEQ applies the EQ predicate on the "owned_by" field.
func OwnedByEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldOwnedBy, v))
}

// OwnedByNEQ applies the NEQ predicate on the "owned_by" field.
func OwnedByNEQ(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldOwnedBy, v))
}

// OwnedByIn applies the In predicate on the "owned_by" field.
func OwnedByIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldOwnedBy, vs...))
}

// OwnedByNotIn applies the NotIn predicate on the "owned_by" field.
func OwnedByNotIn(vs ...int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldOwnedBy, vs...))
}

// OwnedByGT applies the GT predicate on the "owned_by" field.
func OwnedByGT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldOwnedBy, v))
}

// OwnedByGTE applies the GTE predicate on the "owned_by" field.
func OwnedByGTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldOwnedBy, v))
}

// OwnedByLT applies the LT predicate on the "owned_by" field.
func OwnedByLT(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldOwnedBy, v))
}

// OwnedByLTE applies the LTE predicate on the "owned_by" field.
func OwnedByLTE(v int) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldOwnedBy, v))
}

// OwnedByIsNil applies the IsNil predicate on the "owned_by" field.
func OwnedByIsNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIsNull(FieldOwnedBy))
}

// OwnedByNotNil applies the NotNil predicate on the "owned_by" field.
func OwnedByNotNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotNull(FieldOwnedBy))
}

// CanReadEQ applies the EQ predicate on the "can_read" field.
func CanReadEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanRead, v))
}

// CanReadNEQ applies the NEQ predicate on the "can_read" field.
func CanReadNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanRead, v))
}

// CanCreateEQ applies the EQ predicate on the "can_create" field.
func CanCreateEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanCreate, v))
}

// CanCreateNEQ applies the NEQ predicate on the "can_create" field.
func CanCreateNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanCreate, v))
}

// CanUpdateEQ applies the EQ predicate on the "can_update" field.
func CanUpdateEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanUpdate, v))
}

// CanUpdateNEQ applies the NEQ predicate on the "can_update" field.
func CanUpdateNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanUpdate, v))
}

// CanDeleteEQ applies the EQ predicate on the "can_delete" field.
func CanDeleteEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanDelete, v))
}

// CanDeleteNEQ applies the NEQ predicate on the "can_delete" field.
func CanDeleteNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanDelete, v))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPermission applies the HasEdge predicate on the "permission" edge.
func HasPermission() predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PermissionTable, PermissionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPermissionWith applies the HasEdge predicate on the "permission" edge with a given conditions (other predicates).
func HasPermissionWith(preds ...predicate.Permission) predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := newPermissionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.NotPredicates(p))
}
