#!/bin/bash
# Script to generate all Ent schemas for the microservices refactoring

set -e

PROJECT_ROOT="/Users/saurabh/GolandProjects/bolt-microservices"

echo "🚀 Starting comprehensive schema generation..."
echo ""

# Function to create schema file
create_schema() {
    local service=$1
    local filename=$2
    local content=$3

    local filepath="$PROJECT_ROOT/$service/ent/schema/$filename"
    echo "Creating $filepath..."
    echo "$content" > "$filepath"
}

echo "📦 Phase 1: AUTH SERVICE - Creating core schemas..."
echo "✅ Organisation schemas created"
echo "✅ User schemas created"
echo "📝 Creating remaining auth schemas..."

# Note: The actual file creation will be done via the tool
# This script serves as documentation of the implementation plan

echo ""
echo "📊 IMPLEMENTATION SUMMARY:"
echo "================================"
echo ""
echo "AUTH SERVICE (auth/):"
echo "  Core:"
echo "    - user.go ✅"
echo "    - organisation.go ✅"
echo "    - organisation_address.go ✅"
echo "    - organisation_user.go ✅"
echo "    - organisation_role.go ✅"
echo "  To Create:"
echo "    - organisation_role_permission.go"
echo "    - organisation_user_document.go"
echo "    - organisation_user_document_type.go"
echo "    - staff_role.go"
echo "    - api_user.go"
echo "    - login_log.go"
echo "    - profile.go"
echo "    - pinned_device.go"
echo "  Devices (20+ tables):"
echo "    - device.go, device_group.go, device_model.go, etc."
echo "  System:"
echo "    - media_file.go, change_log.go, schedule_task.go"
echo "    - support_ticket.go, export.go, legacy_sync.go, setting.go"
echo "  Whitelabel:"
echo "    - whitelabel.go, domain.go, whitelabel_config.go"
echo "  Map:"
echo "    - geofence.go, poi.go, kml.go, map_config.go, user_config.go"
echo "    - geofence_device_group.go"
echo "  SIM:"
echo "    - sim.go"
echo "  STIQR:"
echo "    - stiqr.go"
echo ""
echo "ATTENDANCE SERVICE (attendance/):"
echo "  - leave_type.go"
echo "  - user_leave_balance.go"
echo "  - leave_request.go"
echo "  - leave_date.go"
echo "  - roster.go"
echo "  - roster_shift.go"
echo "  - attendance.go (with user_snapshot JSON)"
echo "  - attendance_detail.go"
echo "  - roster_schedule.go"
echo "  - user_roster_assignment.go"
echo ""
echo "NOTIFICATION SERVICE (notification/):"
echo "  - notify_event_option.go"
echo "  - notify_channel.go (with org_user_snapshot JSON)"
echo "  - notify_config.go"
echo "  - notify_config_event.go"
echo "  - notify_config_device_group.go (with device_group_snapshot JSON)"
echo "  - notify_config_geofence.go (with geofence_snapshot JSON)"
echo "  - notify_config_channel.go"
echo ""
echo "ROUTE/TRIP SERVICE (route/):"
echo "  - halt_point.go"
echo "  - target.go"
echo "  - route.go"
echo "  - route_halt_point.go"
echo "  - route_halt_point_target.go"
echo "  - route_time_line.go"
echo "  - trip.go (with user_snapshot, device_group_snapshot JSON)"
echo "  - trip_config.go"
echo "  - trip_halt_point.go"
echo "  - trip_halt_point_target.go"
echo "  - trip_halt_point_target_time_line.go"
echo "  - trip_halt_point_time_line.go"
echo "  - trip_time_line.go"
echo "  - adhoc_table.go"
echo "  - shift.go"
echo "  - route_shift.go"
echo ""
echo "YARD SERVICE (yard/):"
echo "  - yard_warehouse.go"
echo "  - yard_warehouse_activity_type.go"
echo "  - yard_warehouse_approval_matrix.go (with org_role_snapshot JSON)"
echo "  - yard_warehouse_dock.go"
echo "  - yard_warehouse_parking.go"
echo "  - yard_warehouse_route.go"
echo "  - yard_warehouse_route_path.go"
echo "  - yard_warehouse_dock_sharing.go"
echo "  - yard_driver_profile.go"
echo "  - yard_material_type.go"
echo "  - yard_material.go"
echo "  - yard_vendor.go"
echo "  - yard_vehicle.go"
echo "  - yard_trip.go (with user_snapshot JSON)"
echo "  - yard_trip_approval.go (with user_snapshot JSON)"
echo "  - yard_trip_status.go (with user_snapshot JSON)"
echo ""
echo "REPORTING SERVICE (reporting/):"
echo "  Reports:"
echo "    - base_report.go (GlobalScope - no org_id)"
echo "    - derived_report.go"
echo "    - organisation_report_access.go"
echo "    - user_report_bookmark.go"
echo "    - support_document.go (GlobalScope)"
echo "    - inspection_report.go (with user_snapshot, device_group_snapshot JSON)"
echo "  Billing/Subscription:"
echo "    - base_addon.go (GlobalScope)"
echo "    - base_license_plan.go (GlobalScope)"
echo "    - base_license_plan_addon.go (GlobalScope)"
echo "    - license.go"
echo "    - subscription_license_order.go"
echo "    - license_order_addon.go"
echo "    - organisation_upgrade.go"
echo "    - upgrade.go (GlobalScope)"
echo "    - upgrade_organisation_price.go"
echo "    - wallet.go"
echo "    - wallet_payment_transaction.go"
echo "    - wallet_transaction.go"
echo ""
echo "================================"
echo ""
echo "⚠️  KEY DESIGN DECISIONS:"
echo "  1. INT64 IDs everywhere (no UUIDs)"
echo "  2. BaseMixin for org-scoped tables"
echo "  3. GlobalScopeMixin for system tables"
echo "  4. JSON columns for cross-service denormalization"
echo "  5. Normalized addresses in auth service"
echo "  6. Soft references (no FK constraints) for cross-service relations"
echo ""
echo "📝 Next: Creating remaining schemas in batches..."

