// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/saurabh/entgo-microservices/microservice/internal/ent/dummy"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *DummyQuery) CollectFields(ctx context.Context, satisfies ...string) (*DummyQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *DummyQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(dummy.Columns))
		selectedFields = []string{dummy.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "createdAt":
			if _, ok := fieldSeen[dummy.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, dummy.FieldCreatedAt)
				fieldSeen[dummy.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[dummy.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, dummy.FieldUpdatedAt)
				fieldSeen[dummy.FieldUpdatedAt] = struct{}{}
			}
		case "tenantID":
			if _, ok := fieldSeen[dummy.FieldTenantID]; !ok {
				selectedFields = append(selectedFields, dummy.FieldTenantID)
				fieldSeen[dummy.FieldTenantID] = struct{}{}
			}
		case "createdBy":
			if _, ok := fieldSeen[dummy.FieldCreatedBy]; !ok {
				selectedFields = append(selectedFields, dummy.FieldCreatedBy)
				fieldSeen[dummy.FieldCreatedBy] = struct{}{}
			}
		case "ownedBy":
			if _, ok := fieldSeen[dummy.FieldOwnedBy]; !ok {
				selectedFields = append(selectedFields, dummy.FieldOwnedBy)
				fieldSeen[dummy.FieldOwnedBy] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[dummy.FieldName]; !ok {
				selectedFields = append(selectedFields, dummy.FieldName)
				fieldSeen[dummy.FieldName] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type dummyPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []DummyPaginateOption
}

func newDummyPaginateArgs(rv map[string]any) *dummyPaginateArgs {
	args := &dummyPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &DummyOrder{Field: &DummyOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithDummyOrder(order))
			}
		case *DummyOrder:
			if v != nil {
				args.opts = append(args.opts, WithDummyOrder(v))
			}
		}
	}
	if v, ok := rv[whereField].(*DummyWhereInput); ok {
		args.opts = append(args.opts, WithDummyFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
