// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/saurabh/entgo-microservices/microservice/ent/schema"
	"github.com/saurabh/entgo-microservices/microservice/internal/ent/dummy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dummyMixin := schema.Dummy{}.Mixin()
	dummyMixinFields0 := dummyMixin[0].Fields()
	_ = dummyMixinFields0
	dummyFields := schema.Dummy{}.Fields()
	_ = dummyFields
	// dummyDescCreatedAt is the schema descriptor for created_at field.
	dummyDescCreatedAt := dummyMixinFields0[1].Descriptor()
	// dummy.DefaultCreatedAt holds the default value on creation for the created_at field.
	dummy.DefaultCreatedAt = dummyDescCreatedAt.Default.(func() time.Time)
	// dummyDescUpdatedAt is the schema descriptor for updated_at field.
	dummyDescUpdatedAt := dummyMixinFields0[2].Descriptor()
	// dummy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dummy.DefaultUpdatedAt = dummyDescUpdatedAt.Default.(func() time.Time)
	// dummy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dummy.UpdateDefaultUpdatedAt = dummyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dummyDescID is the schema descriptor for id field.
	dummyDescID := dummyMixinFields0[0].Descriptor()
	// dummy.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dummy.IDValidator = dummyDescID.Validators[0].(func(int) error)
}
