package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/saurabh/entgo-microservices/microservice/internal/ent"
)

// CreateDummy is the resolver for the createDummy mutation.
func (r *mutationResolver) CreateDummy(ctx context.Context, input ent.CreateDummyInput) (*ent.Dummy, error) {
	return r.Resolver.client.Dummy.Create().SetInput(input).Save(ctx)
}

// CreateBulkDummy is the resolver for the createBulkDummy mutation.
func (r *mutationResolver) CreateBulkDummy(ctx context.Context, input []*ent.CreateDummyInput) ([]*ent.Dummy, error) {
	builders := make([]*ent.DummyCreate, len(input))
	for i, inp := range input {
		builders[i] = r.Resolver.client.Dummy.Create().SetInput(*inp)
	}
	return r.Resolver.client.Dummy.CreateBulk(builders...).Save(ctx)
}

// UpdateDummy is the resolver for the updateDummy mutation.
func (r *mutationResolver) UpdateDummy(ctx context.Context, id int, input ent.UpdateDummyInput) (*ent.Dummy, error) {
	return r.Resolver.client.Dummy.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteDummy is the resolver for the deleteDummy mutation.
func (r *mutationResolver) DeleteDummy(ctx context.Context, id int) (bool, error) {
	err := r.Resolver.client.Dummy.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return false, err
	}
	return true, nil
}

// DummyByID is the resolver for the DummyByID field.
func (r *queryResolver) DummyByID(ctx context.Context, id int) (*ent.Dummy, error) {
	user, err := r.Resolver.gatewayClient.Services().Auth().GetUserByID(ctx, 1)
	if err != nil {
		fmt.Printf("⚠️  Failed to get user from auth service: %v\n", err)
	} else {
		fmt.Printf("✅ Successfully fetched user from Auth service via gRPC:\n")
		fmt.Printf("   User ID: %d\n", user.Id)
		fmt.Printf("   Email: %s\n", user.Email)
		fmt.Printf("   Username: %s\n", user.Username)
	}
	return r.Resolver.client.Dummy.Get(ctx, id)
}

// Dummies is the resolver for the Dummies field.
func (r *queryResolver) Dummies(ctx context.Context, first *int, after *entgql.Cursor[int], last *int, before *entgql.Cursor[int], orderBy *ent.DummyOrder, where *ent.DummyWhereInput) (*ent.DummyConnection, error) {
	return r.Resolver.client.Dummy.Query().Paginate(ctx, after, first, before, last, ent.WithDummyFilter(where.Filter), ent.WithDummyOrder(orderBy))
}
