// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dummy2/dummy2.proto

package dummy2v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dummy2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Category      string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Priority      int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Notes         string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dummy2) Reset() {
	*x = Dummy2{}
	mi := &file_dummy2_dummy2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dummy2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dummy2) ProtoMessage() {}

func (x *Dummy2) ProtoReflect() protoreflect.Message {
	mi := &file_dummy2_dummy2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dummy2.ProtoReflect.Descriptor instead.
func (*Dummy2) Descriptor() ([]byte, []int) {
	return file_dummy2_dummy2_proto_rawDescGZIP(), []int{0}
}

func (x *Dummy2) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dummy2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dummy2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dummy2) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Dummy2) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Dummy2) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Dummy2) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Dummy2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Dummy2) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Dummy2) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Dummy2) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Dummy2) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Dummy2) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetDummy2ByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDummy2ByIDRequest) Reset() {
	*x = GetDummy2ByIDRequest{}
	mi := &file_dummy2_dummy2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDummy2ByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummy2ByIDRequest) ProtoMessage() {}

func (x *GetDummy2ByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummy2_dummy2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummy2ByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDummy2ByIDRequest) Descriptor() ([]byte, []int) {
	return file_dummy2_dummy2_proto_rawDescGZIP(), []int{1}
}

func (x *GetDummy2ByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDummy2ByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy2        *Dummy2                `protobuf:"bytes,1,opt,name=dummy2,proto3" json:"dummy2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDummy2ByIDResponse) Reset() {
	*x = GetDummy2ByIDResponse{}
	mi := &file_dummy2_dummy2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDummy2ByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummy2ByIDResponse) ProtoMessage() {}

func (x *GetDummy2ByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dummy2_dummy2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummy2ByIDResponse.ProtoReflect.Descriptor instead.
func (*GetDummy2ByIDResponse) Descriptor() ([]byte, []int) {
	return file_dummy2_dummy2_proto_rawDescGZIP(), []int{2}
}

func (x *GetDummy2ByIDResponse) GetDummy2() *Dummy2 {
	if x != nil {
		return x.Dummy2
	}
	return nil
}

type GetDummy2SByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDummy2SByIDsRequest) Reset() {
	*x = GetDummy2SByIDsRequest{}
	mi := &file_dummy2_dummy2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDummy2SByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummy2SByIDsRequest) ProtoMessage() {}

func (x *GetDummy2SByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummy2_dummy2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummy2SByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetDummy2SByIDsRequest) Descriptor() ([]byte, []int) {
	return file_dummy2_dummy2_proto_rawDescGZIP(), []int{3}
}

func (x *GetDummy2SByIDsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetDummy2SByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy2S       []*Dummy2              `protobuf:"bytes,1,rep,name=dummy2s,proto3" json:"dummy2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDummy2SByIDsResponse) Reset() {
	*x = GetDummy2SByIDsResponse{}
	mi := &file_dummy2_dummy2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDummy2SByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummy2SByIDsResponse) ProtoMessage() {}

func (x *GetDummy2SByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dummy2_dummy2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummy2SByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetDummy2SByIDsResponse) Descriptor() ([]byte, []int) {
	return file_dummy2_dummy2_proto_rawDescGZIP(), []int{4}
}

func (x *GetDummy2SByIDsResponse) GetDummy2S() []*Dummy2 {
	if x != nil {
		return x.Dummy2S
	}
	return nil
}

var File_dummy2_dummy2_proto protoreflect.FileDescriptor

const file_dummy2_dummy2_proto_rawDesc = "" +
	"\n" +
	"\x13dummy2/dummy2.proto\x12\tdummy2.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\x06Dummy2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"&\n" +
	"\x14GetDummy2ByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"B\n" +
	"\x15GetDummy2ByIDResponse\x12)\n" +
	"\x06dummy2\x18\x01 \x01(\v2\x11.dummy2.v1.Dummy2R\x06dummy2\"*\n" +
	"\x16GetDummy2sByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"F\n" +
	"\x17GetDummy2sByIDsResponse\x12+\n" +
	"\adummy2s\x18\x01 \x03(\v2\x11.dummy2.v1.Dummy2R\adummy2s2\xbd\x01\n" +
	"\rDummy2Service\x12R\n" +
	"\rGetDummy2ByID\x12\x1f.dummy2.v1.GetDummy2ByIDRequest\x1a .dummy2.v1.GetDummy2ByIDResponse\x12X\n" +
	"\x0fGetDummy2sByIDs\x12!.dummy2.v1.GetDummy2sByIDsRequest\x1a\".dummy2.v1.GetDummy2sByIDsResponseBEZCgithub.com/saurabh/entgo-microservices/pkg/proto/dummy2/v1;dummy2v1b\x06proto3"

var (
	file_dummy2_dummy2_proto_rawDescOnce sync.Once
	file_dummy2_dummy2_proto_rawDescData []byte
)

func file_dummy2_dummy2_proto_rawDescGZIP() []byte {
	file_dummy2_dummy2_proto_rawDescOnce.Do(func() {
		file_dummy2_dummy2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dummy2_dummy2_proto_rawDesc), len(file_dummy2_dummy2_proto_rawDesc)))
	})
	return file_dummy2_dummy2_proto_rawDescData
}

var file_dummy2_dummy2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dummy2_dummy2_proto_goTypes = []any{
	(*Dummy2)(nil),                  // 0: dummy2.v1.Dummy2
	(*GetDummy2ByIDRequest)(nil),    // 1: dummy2.v1.GetDummy2ByIDRequest
	(*GetDummy2ByIDResponse)(nil),   // 2: dummy2.v1.GetDummy2ByIDResponse
	(*GetDummy2SByIDsRequest)(nil),  // 3: dummy2.v1.GetDummy2sByIDsRequest
	(*GetDummy2SByIDsResponse)(nil), // 4: dummy2.v1.GetDummy2sByIDsResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_dummy2_dummy2_proto_depIdxs = []int32{
	5, // 0: dummy2.v1.Dummy2.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: dummy2.v1.Dummy2.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: dummy2.v1.GetDummy2ByIDResponse.dummy2:type_name -> dummy2.v1.Dummy2
	0, // 3: dummy2.v1.GetDummy2sByIDsResponse.dummy2s:type_name -> dummy2.v1.Dummy2
	1, // 4: dummy2.v1.Dummy2Service.GetDummy2ByID:input_type -> dummy2.v1.GetDummy2ByIDRequest
	3, // 5: dummy2.v1.Dummy2Service.GetDummy2sByIDs:input_type -> dummy2.v1.GetDummy2sByIDsRequest
	2, // 6: dummy2.v1.Dummy2Service.GetDummy2ByID:output_type -> dummy2.v1.GetDummy2ByIDResponse
	4, // 7: dummy2.v1.Dummy2Service.GetDummy2sByIDs:output_type -> dummy2.v1.GetDummy2sByIDsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dummy2_dummy2_proto_init() }
func file_dummy2_dummy2_proto_init() {
	if File_dummy2_dummy2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dummy2_dummy2_proto_rawDesc), len(file_dummy2_dummy2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummy2_dummy2_proto_goTypes,
		DependencyIndexes: file_dummy2_dummy2_proto_depIdxs,
		MessageInfos:      file_dummy2_dummy2_proto_msgTypes,
	}.Build()
	File_dummy2_dummy2_proto = out.File
	file_dummy2_dummy2_proto_goTypes = nil
	file_dummy2_dummy2_proto_depIdxs = nil
}
