// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: rolepermission/rolepermission.proto

package rolepermissionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RolePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CanRead       bool                   `protobuf:"varint,2,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanCreate     bool                   `protobuf:"varint,3,opt,name=can_create,json=canCreate,proto3" json:"can_create,omitempty"`
	CanUpdate     bool                   `protobuf:"varint,4,opt,name=can_update,json=canUpdate,proto3" json:"can_update,omitempty"`
	CanDelete     bool                   `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermission) Reset() {
	*x = RolePermission{}
	mi := &file_rolepermission_rolepermission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermission) ProtoMessage() {}

func (x *RolePermission) ProtoReflect() protoreflect.Message {
	mi := &file_rolepermission_rolepermission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermission.ProtoReflect.Descriptor instead.
func (*RolePermission) Descriptor() ([]byte, []int) {
	return file_rolepermission_rolepermission_proto_rawDescGZIP(), []int{0}
}

func (x *RolePermission) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePermission) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *RolePermission) GetCanCreate() bool {
	if x != nil {
		return x.CanCreate
	}
	return false
}

func (x *RolePermission) GetCanUpdate() bool {
	if x != nil {
		return x.CanUpdate
	}
	return false
}

func (x *RolePermission) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *RolePermission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RolePermission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetRolePermissionByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionByIDRequest) Reset() {
	*x = GetRolePermissionByIDRequest{}
	mi := &file_rolepermission_rolepermission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionByIDRequest) ProtoMessage() {}

func (x *GetRolePermissionByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolepermission_rolepermission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionByIDRequest) Descriptor() ([]byte, []int) {
	return file_rolepermission_rolepermission_proto_rawDescGZIP(), []int{1}
}

func (x *GetRolePermissionByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRolePermissionByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rolepermission *RolePermission        `protobuf:"bytes,1,opt,name=rolepermission,proto3" json:"rolepermission,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRolePermissionByIDResponse) Reset() {
	*x = GetRolePermissionByIDResponse{}
	mi := &file_rolepermission_rolepermission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionByIDResponse) ProtoMessage() {}

func (x *GetRolePermissionByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolepermission_rolepermission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionByIDResponse) Descriptor() ([]byte, []int) {
	return file_rolepermission_rolepermission_proto_rawDescGZIP(), []int{2}
}

func (x *GetRolePermissionByIDResponse) GetRolepermission() *RolePermission {
	if x != nil {
		return x.Rolepermission
	}
	return nil
}

type GetRolePermissionsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsByIDsRequest) Reset() {
	*x = GetRolePermissionsByIDsRequest{}
	mi := &file_rolepermission_rolepermission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsByIDsRequest) ProtoMessage() {}

func (x *GetRolePermissionsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolepermission_rolepermission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_rolepermission_rolepermission_proto_rawDescGZIP(), []int{3}
}

func (x *GetRolePermissionsByIDsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetRolePermissionsByIDsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rolepermissions []*RolePermission      `protobuf:"bytes,1,rep,name=rolepermissions,proto3" json:"rolepermissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRolePermissionsByIDsResponse) Reset() {
	*x = GetRolePermissionsByIDsResponse{}
	mi := &file_rolepermission_rolepermission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsByIDsResponse) ProtoMessage() {}

func (x *GetRolePermissionsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolepermission_rolepermission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_rolepermission_rolepermission_proto_rawDescGZIP(), []int{4}
}

func (x *GetRolePermissionsByIDsResponse) GetRolepermissions() []*RolePermission {
	if x != nil {
		return x.Rolepermissions
	}
	return nil
}

var File_rolepermission_rolepermission_proto protoreflect.FileDescriptor

const file_rolepermission_rolepermission_proto_rawDesc = "" +
	"\n" +
	"#rolepermission/rolepermission.proto\x12\x11rolepermission.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x0eRolePermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bcan_read\x18\x02 \x01(\bR\acanRead\x12\x1d\n" +
	"\n" +
	"can_create\x18\x03 \x01(\bR\tcanCreate\x12\x1d\n" +
	"\n" +
	"can_update\x18\x04 \x01(\bR\tcanUpdate\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x05 \x01(\bR\tcanDelete\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\".\n" +
	"\x1cGetRolePermissionByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"j\n" +
	"\x1dGetRolePermissionByIDResponse\x12I\n" +
	"\x0erolepermission\x18\x01 \x01(\v2!.rolepermission.v1.RolePermissionR\x0erolepermission\"2\n" +
	"\x1eGetRolePermissionsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"n\n" +
	"\x1fGetRolePermissionsByIDsResponse\x12K\n" +
	"\x0frolepermissions\x18\x01 \x03(\v2!.rolepermission.v1.RolePermissionR\x0frolepermissions2\x96\x02\n" +
	"\x15RolePermissionService\x12z\n" +
	"\x15GetRolePermissionByID\x12/.rolepermission.v1.GetRolePermissionByIDRequest\x1a0.rolepermission.v1.GetRolePermissionByIDResponse\x12\x80\x01\n" +
	"\x17GetRolePermissionsByIDs\x121.rolepermission.v1.GetRolePermissionsByIDsRequest\x1a2.rolepermission.v1.GetRolePermissionsByIDsResponseBUZSgithub.com/saurabh/entgo-microservices/pkg/proto/rolepermission/v1;rolepermissionv1b\x06proto3"

var (
	file_rolepermission_rolepermission_proto_rawDescOnce sync.Once
	file_rolepermission_rolepermission_proto_rawDescData []byte
)

func file_rolepermission_rolepermission_proto_rawDescGZIP() []byte {
	file_rolepermission_rolepermission_proto_rawDescOnce.Do(func() {
		file_rolepermission_rolepermission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rolepermission_rolepermission_proto_rawDesc), len(file_rolepermission_rolepermission_proto_rawDesc)))
	})
	return file_rolepermission_rolepermission_proto_rawDescData
}

var file_rolepermission_rolepermission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rolepermission_rolepermission_proto_goTypes = []any{
	(*RolePermission)(nil),                  // 0: rolepermission.v1.RolePermission
	(*GetRolePermissionByIDRequest)(nil),    // 1: rolepermission.v1.GetRolePermissionByIDRequest
	(*GetRolePermissionByIDResponse)(nil),   // 2: rolepermission.v1.GetRolePermissionByIDResponse
	(*GetRolePermissionsByIDsRequest)(nil),  // 3: rolepermission.v1.GetRolePermissionsByIDsRequest
	(*GetRolePermissionsByIDsResponse)(nil), // 4: rolepermission.v1.GetRolePermissionsByIDsResponse
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
}
var file_rolepermission_rolepermission_proto_depIdxs = []int32{
	5, // 0: rolepermission.v1.RolePermission.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: rolepermission.v1.RolePermission.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: rolepermission.v1.GetRolePermissionByIDResponse.rolepermission:type_name -> rolepermission.v1.RolePermission
	0, // 3: rolepermission.v1.GetRolePermissionsByIDsResponse.rolepermissions:type_name -> rolepermission.v1.RolePermission
	1, // 4: rolepermission.v1.RolePermissionService.GetRolePermissionByID:input_type -> rolepermission.v1.GetRolePermissionByIDRequest
	3, // 5: rolepermission.v1.RolePermissionService.GetRolePermissionsByIDs:input_type -> rolepermission.v1.GetRolePermissionsByIDsRequest
	2, // 6: rolepermission.v1.RolePermissionService.GetRolePermissionByID:output_type -> rolepermission.v1.GetRolePermissionByIDResponse
	4, // 7: rolepermission.v1.RolePermissionService.GetRolePermissionsByIDs:output_type -> rolepermission.v1.GetRolePermissionsByIDsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rolepermission_rolepermission_proto_init() }
func file_rolepermission_rolepermission_proto_init() {
	if File_rolepermission_rolepermission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rolepermission_rolepermission_proto_rawDesc), len(file_rolepermission_rolepermission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rolepermission_rolepermission_proto_goTypes,
		DependencyIndexes: file_rolepermission_rolepermission_proto_depIdxs,
		MessageInfos:      file_rolepermission_rolepermission_proto_msgTypes,
	}.Build()
	File_rolepermission_rolepermission_proto = out.File
	file_rolepermission_rolepermission_proto_goTypes = nil
	file_rolepermission_rolepermission_proto_depIdxs = nil
}
