// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/permission"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/predicate"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/rolepermission"
)

// PermissionUpdate is the builder for updating Permission entities.
type PermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *PermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdate) Where(ps ...predicate.Permission) *PermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionUpdate) SetUpdatedAt(v time.Time) *PermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PermissionUpdate) SetCreatedBy(v int) *PermissionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableCreatedBy(v *int) *PermissionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PermissionUpdate) AddCreatedBy(v int) *PermissionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PermissionUpdate) ClearCreatedBy() *PermissionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *PermissionUpdate) SetOwnedBy(v int) *PermissionUpdate {
	_u.mutation.ResetOwnedBy()
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableOwnedBy(v *int) *PermissionUpdate {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// AddOwnedBy adds value to the "owned_by" field.
func (_u *PermissionUpdate) AddOwnedBy(v int) *PermissionUpdate {
	_u.mutation.AddOwnedBy(v)
	return _u
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (_u *PermissionUpdate) ClearOwnedBy() *PermissionUpdate {
	_u.mutation.ClearOwnedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *PermissionUpdate) SetTenantID(v int) *PermissionUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableTenantID(v *int) *PermissionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *PermissionUpdate) AddTenantID(v int) *PermissionUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PermissionUpdate) SetName(v string) *PermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableName(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PermissionUpdate) SetDisplayName(v string) *PermissionUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableDisplayName(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PermissionUpdate) SetDescription(v string) *PermissionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableDescription(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PermissionUpdate) ClearDescription() *PermissionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetResource sets the "resource" field.
func (_u *PermissionUpdate) SetResource(v string) *PermissionUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableResource(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PermissionUpdate) SetIsActive(v bool) *PermissionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableIsActive(v *bool) *PermissionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *PermissionUpdate) AddRolePermissionIDs(ids ...int) *PermissionUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *PermissionUpdate) AddRolePermissions(v ...*RolePermission) *PermissionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdate) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *PermissionUpdate) ClearRolePermissions() *PermissionUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *PermissionUpdate) RemoveRolePermissionIDs(ids ...int) *PermissionUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *PermissionUpdate) RemoveRolePermissions(v ...*RolePermission) *PermissionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := permission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := permission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Permission.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := permission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Permission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := permission.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Permission.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := permission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Permission.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := permission.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "Permission.resource": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(permission.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(permission.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(permission.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(permission.FieldOwnedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnedBy(); ok {
		_spec.AddField(permission.FieldOwnedBy, field.TypeInt, value)
	}
	if _u.mutation.OwnedByCleared() {
		_spec.ClearField(permission.FieldOwnedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(permission.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(permission.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(permission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(permission.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(permission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(permission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(permission.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(permission.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionUpdateOne is the builder for updating a single Permission entity.
type PermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionUpdateOne) SetUpdatedAt(v time.Time) *PermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PermissionUpdateOne) SetCreatedBy(v int) *PermissionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableCreatedBy(v *int) *PermissionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PermissionUpdateOne) AddCreatedBy(v int) *PermissionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PermissionUpdateOne) ClearCreatedBy() *PermissionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *PermissionUpdateOne) SetOwnedBy(v int) *PermissionUpdateOne {
	_u.mutation.ResetOwnedBy()
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableOwnedBy(v *int) *PermissionUpdateOne {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// AddOwnedBy adds value to the "owned_by" field.
func (_u *PermissionUpdateOne) AddOwnedBy(v int) *PermissionUpdateOne {
	_u.mutation.AddOwnedBy(v)
	return _u
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (_u *PermissionUpdateOne) ClearOwnedBy() *PermissionUpdateOne {
	_u.mutation.ClearOwnedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *PermissionUpdateOne) SetTenantID(v int) *PermissionUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableTenantID(v *int) *PermissionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *PermissionUpdateOne) AddTenantID(v int) *PermissionUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PermissionUpdateOne) SetName(v string) *PermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableName(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PermissionUpdateOne) SetDisplayName(v string) *PermissionUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableDisplayName(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PermissionUpdateOne) SetDescription(v string) *PermissionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableDescription(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PermissionUpdateOne) ClearDescription() *PermissionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetResource sets the "resource" field.
func (_u *PermissionUpdateOne) SetResource(v string) *PermissionUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableResource(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PermissionUpdateOne) SetIsActive(v bool) *PermissionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableIsActive(v *bool) *PermissionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *PermissionUpdateOne) AddRolePermissionIDs(ids ...int) *PermissionUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *PermissionUpdateOne) AddRolePermissions(v ...*RolePermission) *PermissionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdateOne) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *PermissionUpdateOne) ClearRolePermissions() *PermissionUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *PermissionUpdateOne) RemoveRolePermissionIDs(ids ...int) *PermissionUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *PermissionUpdateOne) RemoveRolePermissions(v ...*RolePermission) *PermissionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdateOne) Where(ps ...predicate.Permission) *PermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionUpdateOne) Select(field string, fields ...string) *PermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Permission entity.
func (_u *PermissionUpdateOne) Save(ctx context.Context) (*Permission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdateOne) SaveX(ctx context.Context) *Permission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := permission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := permission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Permission.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := permission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Permission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := permission.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Permission.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := permission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Permission.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := permission.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "Permission.resource": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PermissionUpdateOne) sqlSave(ctx context.Context) (_node *Permission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permission.FieldID)
		for _, f := range fields {
			if !permission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(permission.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(permission.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(permission.FieldCreatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(permission.FieldOwnedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnedBy(); ok {
		_spec.AddField(permission.FieldOwnedBy, field.TypeInt, value)
	}
	if _u.mutation.OwnedByCleared() {
		_spec.ClearField(permission.FieldOwnedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(permission.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(permission.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(permission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(permission.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(permission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(permission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(permission.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(permission.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Permission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
