// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saurabh/entgo-microservices/test-service/internal/ent/dummy"
)

// DummyCreate is the builder for creating a Dummy entity.
type DummyCreate struct {
	config
	mutation *DummyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DummyCreate) SetCreatedAt(v time.Time) *DummyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DummyCreate) SetNillableCreatedAt(v *time.Time) *DummyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DummyCreate) SetUpdatedAt(v time.Time) *DummyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DummyCreate) SetNillableUpdatedAt(v *time.Time) *DummyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *DummyCreate) SetTenantID(v int) *DummyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *DummyCreate) SetNillableTenantID(v *int) *DummyCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DummyCreate) SetCreatedBy(v int) *DummyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DummyCreate) SetNillableCreatedBy(v *int) *DummyCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetOwnedBy sets the "owned_by" field.
func (_c *DummyCreate) SetOwnedBy(v int) *DummyCreate {
	_c.mutation.SetOwnedBy(v)
	return _c
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_c *DummyCreate) SetNillableOwnedBy(v *int) *DummyCreate {
	if v != nil {
		_c.SetOwnedBy(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DummyCreate) SetName(v string) *DummyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DummyCreate) SetNillableName(v *string) *DummyCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DummyCreate) SetID(v int) *DummyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DummyMutation object of the builder.
func (_c *DummyCreate) Mutation() *DummyMutation {
	return _c.mutation
}

// Save creates the Dummy in the database.
func (_c *DummyCreate) Save(ctx context.Context) (*Dummy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DummyCreate) SaveX(ctx context.Context) *Dummy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DummyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DummyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DummyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if dummy.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized dummy.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := dummy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if dummy.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized dummy.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := dummy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DummyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Dummy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Dummy.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := dummy.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Dummy.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DummyCreate) sqlSave(ctx context.Context) (*Dummy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DummyCreate) createSpec() (*Dummy, *sqlgraph.CreateSpec) {
	var (
		_node = &Dummy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dummy.Table, sqlgraph.NewFieldSpec(dummy.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dummy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dummy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(dummy.FieldTenantID, field.TypeInt, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(dummy.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.OwnedBy(); ok {
		_spec.SetField(dummy.FieldOwnedBy, field.TypeInt, value)
		_node.OwnedBy = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dummy.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dummy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DummyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DummyCreate) OnConflict(opts ...sql.ConflictOption) *DummyUpsertOne {
	_c.conflict = opts
	return &DummyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dummy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DummyCreate) OnConflictColumns(columns ...string) *DummyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DummyUpsertOne{
		create: _c,
	}
}

type (
	// DummyUpsertOne is the builder for "upsert"-ing
	//  one Dummy node.
	DummyUpsertOne struct {
		create *DummyCreate
	}

	// DummyUpsert is the "OnConflict" setter.
	DummyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DummyUpsert) SetUpdatedAt(v time.Time) *DummyUpsert {
	u.Set(dummy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DummyUpsert) UpdateUpdatedAt() *DummyUpsert {
	u.SetExcluded(dummy.FieldUpdatedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DummyUpsert) SetTenantID(v int) *DummyUpsert {
	u.Set(dummy.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DummyUpsert) UpdateTenantID() *DummyUpsert {
	u.SetExcluded(dummy.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *DummyUpsert) AddTenantID(v int) *DummyUpsert {
	u.Add(dummy.FieldTenantID, v)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *DummyUpsert) ClearTenantID() *DummyUpsert {
	u.SetNull(dummy.FieldTenantID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DummyUpsert) SetCreatedBy(v int) *DummyUpsert {
	u.Set(dummy.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DummyUpsert) UpdateCreatedBy() *DummyUpsert {
	u.SetExcluded(dummy.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DummyUpsert) AddCreatedBy(v int) *DummyUpsert {
	u.Add(dummy.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DummyUpsert) ClearCreatedBy() *DummyUpsert {
	u.SetNull(dummy.FieldCreatedBy)
	return u
}

// SetOwnedBy sets the "owned_by" field.
func (u *DummyUpsert) SetOwnedBy(v int) *DummyUpsert {
	u.Set(dummy.FieldOwnedBy, v)
	return u
}

// UpdateOwnedBy sets the "owned_by" field to the value that was provided on create.
func (u *DummyUpsert) UpdateOwnedBy() *DummyUpsert {
	u.SetExcluded(dummy.FieldOwnedBy)
	return u
}

// AddOwnedBy adds v to the "owned_by" field.
func (u *DummyUpsert) AddOwnedBy(v int) *DummyUpsert {
	u.Add(dummy.FieldOwnedBy, v)
	return u
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (u *DummyUpsert) ClearOwnedBy() *DummyUpsert {
	u.SetNull(dummy.FieldOwnedBy)
	return u
}

// SetName sets the "name" field.
func (u *DummyUpsert) SetName(v string) *DummyUpsert {
	u.Set(dummy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DummyUpsert) UpdateName() *DummyUpsert {
	u.SetExcluded(dummy.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *DummyUpsert) ClearName() *DummyUpsert {
	u.SetNull(dummy.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Dummy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dummy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DummyUpsertOne) UpdateNewValues() *DummyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dummy.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dummy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Dummy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DummyUpsertOne) Ignore() *DummyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DummyUpsertOne) DoNothing() *DummyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DummyCreate.OnConflict
// documentation for more info.
func (u *DummyUpsertOne) Update(set func(*DummyUpsert)) *DummyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DummyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DummyUpsertOne) SetUpdatedAt(v time.Time) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DummyUpsertOne) UpdateUpdatedAt() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *DummyUpsertOne) SetTenantID(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *DummyUpsertOne) AddTenantID(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DummyUpsertOne) UpdateTenantID() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *DummyUpsertOne) ClearTenantID() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.ClearTenantID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DummyUpsertOne) SetCreatedBy(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DummyUpsertOne) AddCreatedBy(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DummyUpsertOne) UpdateCreatedBy() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DummyUpsertOne) ClearCreatedBy() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.ClearCreatedBy()
	})
}

// SetOwnedBy sets the "owned_by" field.
func (u *DummyUpsertOne) SetOwnedBy(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.SetOwnedBy(v)
	})
}

// AddOwnedBy adds v to the "owned_by" field.
func (u *DummyUpsertOne) AddOwnedBy(v int) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.AddOwnedBy(v)
	})
}

// UpdateOwnedBy sets the "owned_by" field to the value that was provided on create.
func (u *DummyUpsertOne) UpdateOwnedBy() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateOwnedBy()
	})
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (u *DummyUpsertOne) ClearOwnedBy() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.ClearOwnedBy()
	})
}

// SetName sets the "name" field.
func (u *DummyUpsertOne) SetName(v string) *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DummyUpsertOne) UpdateName() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *DummyUpsertOne) ClearName() *DummyUpsertOne {
	return u.Update(func(s *DummyUpsert) {
		s.ClearName()
	})
}

// Exec executes the query.
func (u *DummyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DummyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DummyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DummyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DummyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DummyCreateBulk is the builder for creating many Dummy entities in bulk.
type DummyCreateBulk struct {
	config
	err      error
	builders []*DummyCreate
	conflict []sql.ConflictOption
}

// Save creates the Dummy entities in the database.
func (_c *DummyCreateBulk) Save(ctx context.Context) ([]*Dummy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Dummy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DummyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DummyCreateBulk) SaveX(ctx context.Context) []*Dummy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DummyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DummyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Dummy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DummyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DummyCreateBulk) OnConflict(opts ...sql.ConflictOption) *DummyUpsertBulk {
	_c.conflict = opts
	return &DummyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Dummy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DummyCreateBulk) OnConflictColumns(columns ...string) *DummyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DummyUpsertBulk{
		create: _c,
	}
}

// DummyUpsertBulk is the builder for "upsert"-ing
// a bulk of Dummy nodes.
type DummyUpsertBulk struct {
	create *DummyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Dummy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dummy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DummyUpsertBulk) UpdateNewValues() *DummyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dummy.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dummy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Dummy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DummyUpsertBulk) Ignore() *DummyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DummyUpsertBulk) DoNothing() *DummyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DummyCreateBulk.OnConflict
// documentation for more info.
func (u *DummyUpsertBulk) Update(set func(*DummyUpsert)) *DummyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DummyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DummyUpsertBulk) SetUpdatedAt(v time.Time) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DummyUpsertBulk) UpdateUpdatedAt() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *DummyUpsertBulk) SetTenantID(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *DummyUpsertBulk) AddTenantID(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DummyUpsertBulk) UpdateTenantID() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *DummyUpsertBulk) ClearTenantID() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.ClearTenantID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DummyUpsertBulk) SetCreatedBy(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DummyUpsertBulk) AddCreatedBy(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DummyUpsertBulk) UpdateCreatedBy() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DummyUpsertBulk) ClearCreatedBy() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.ClearCreatedBy()
	})
}

// SetOwnedBy sets the "owned_by" field.
func (u *DummyUpsertBulk) SetOwnedBy(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.SetOwnedBy(v)
	})
}

// AddOwnedBy adds v to the "owned_by" field.
func (u *DummyUpsertBulk) AddOwnedBy(v int) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.AddOwnedBy(v)
	})
}

// UpdateOwnedBy sets the "owned_by" field to the value that was provided on create.
func (u *DummyUpsertBulk) UpdateOwnedBy() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateOwnedBy()
	})
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (u *DummyUpsertBulk) ClearOwnedBy() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.ClearOwnedBy()
	})
}

// SetName sets the "name" field.
func (u *DummyUpsertBulk) SetName(v string) *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DummyUpsertBulk) UpdateName() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *DummyUpsertBulk) ClearName() *DummyUpsertBulk {
	return u.Update(func(s *DummyUpsert) {
		s.ClearName()
	})
}

// Exec executes the query.
func (u *DummyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DummyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DummyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DummyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
