// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saurabh/entgo-microservices/test-service/internal/ent/dummy"
	"github.com/saurabh/entgo-microservices/test-service/internal/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDummy = "Dummy"
)

// DummyMutation represents an operation that mutates the Dummy nodes in the graph.
type DummyMutation struct {
	config
	op            Op
	typ           string
	id            *int
	created_at    *time.Time
	updated_at    *time.Time
	tenant_id     *int
	addtenant_id  *int
	created_by    *int
	addcreated_by *int
	owned_by      *int
	addowned_by   *int
	name          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Dummy, error)
	predicates    []predicate.Dummy
}

var _ ent.Mutation = (*DummyMutation)(nil)

// dummyOption allows management of the mutation configuration using functional options.
type dummyOption func(*DummyMutation)

// newDummyMutation creates new mutation for the Dummy entity.
func newDummyMutation(c config, op Op, opts ...dummyOption) *DummyMutation {
	m := &DummyMutation{
		config:        c,
		op:            op,
		typ:           TypeDummy,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDummyID sets the ID field of the mutation.
func withDummyID(id int) dummyOption {
	return func(m *DummyMutation) {
		var (
			err   error
			once  sync.Once
			value *Dummy
		)
		m.oldValue = func(ctx context.Context) (*Dummy, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Dummy.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDummy sets the old Dummy of the mutation.
func withDummy(node *Dummy) dummyOption {
	return func(m *DummyMutation) {
		m.oldValue = func(context.Context) (*Dummy, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DummyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DummyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Dummy entities.
func (m *DummyMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DummyMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DummyMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Dummy.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *DummyMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DummyMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DummyMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DummyMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DummyMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DummyMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTenantID sets the "tenant_id" field.
func (m *DummyMutation) SetTenantID(i int) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *DummyMutation) TenantID() (r int, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldTenantID(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *DummyMutation) AddTenantID(i int) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *DummyMutation) AddedTenantID() (r int, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearTenantID clears the value of the "tenant_id" field.
func (m *DummyMutation) ClearTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	m.clearedFields[dummy.FieldTenantID] = struct{}{}
}

// TenantIDCleared returns if the "tenant_id" field was cleared in this mutation.
func (m *DummyMutation) TenantIDCleared() bool {
	_, ok := m.clearedFields[dummy.FieldTenantID]
	return ok
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *DummyMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	delete(m.clearedFields, dummy.FieldTenantID)
}

// SetCreatedBy sets the "created_by" field.
func (m *DummyMutation) SetCreatedBy(i int) {
	m.created_by = &i
	m.addcreated_by = nil
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *DummyMutation) CreatedBy() (r int, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldCreatedBy(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// AddCreatedBy adds i to the "created_by" field.
func (m *DummyMutation) AddCreatedBy(i int) {
	if m.addcreated_by != nil {
		*m.addcreated_by += i
	} else {
		m.addcreated_by = &i
	}
}

// AddedCreatedBy returns the value that was added to the "created_by" field in this mutation.
func (m *DummyMutation) AddedCreatedBy() (r int, exists bool) {
	v := m.addcreated_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearCreatedBy clears the value of the "created_by" field.
func (m *DummyMutation) ClearCreatedBy() {
	m.created_by = nil
	m.addcreated_by = nil
	m.clearedFields[dummy.FieldCreatedBy] = struct{}{}
}

// CreatedByCleared returns if the "created_by" field was cleared in this mutation.
func (m *DummyMutation) CreatedByCleared() bool {
	_, ok := m.clearedFields[dummy.FieldCreatedBy]
	return ok
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *DummyMutation) ResetCreatedBy() {
	m.created_by = nil
	m.addcreated_by = nil
	delete(m.clearedFields, dummy.FieldCreatedBy)
}

// SetOwnedBy sets the "owned_by" field.
func (m *DummyMutation) SetOwnedBy(i int) {
	m.owned_by = &i
	m.addowned_by = nil
}

// OwnedBy returns the value of the "owned_by" field in the mutation.
func (m *DummyMutation) OwnedBy() (r int, exists bool) {
	v := m.owned_by
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnedBy returns the old "owned_by" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldOwnedBy(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnedBy: %w", err)
	}
	return oldValue.OwnedBy, nil
}

// AddOwnedBy adds i to the "owned_by" field.
func (m *DummyMutation) AddOwnedBy(i int) {
	if m.addowned_by != nil {
		*m.addowned_by += i
	} else {
		m.addowned_by = &i
	}
}

// AddedOwnedBy returns the value that was added to the "owned_by" field in this mutation.
func (m *DummyMutation) AddedOwnedBy() (r int, exists bool) {
	v := m.addowned_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearOwnedBy clears the value of the "owned_by" field.
func (m *DummyMutation) ClearOwnedBy() {
	m.owned_by = nil
	m.addowned_by = nil
	m.clearedFields[dummy.FieldOwnedBy] = struct{}{}
}

// OwnedByCleared returns if the "owned_by" field was cleared in this mutation.
func (m *DummyMutation) OwnedByCleared() bool {
	_, ok := m.clearedFields[dummy.FieldOwnedBy]
	return ok
}

// ResetOwnedBy resets all changes to the "owned_by" field.
func (m *DummyMutation) ResetOwnedBy() {
	m.owned_by = nil
	m.addowned_by = nil
	delete(m.clearedFields, dummy.FieldOwnedBy)
}

// SetName sets the "name" field.
func (m *DummyMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DummyMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Dummy entity.
// If the Dummy object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DummyMutation) OldName(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *DummyMutation) ClearName() {
	m.name = nil
	m.clearedFields[dummy.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *DummyMutation) NameCleared() bool {
	_, ok := m.clearedFields[dummy.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *DummyMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, dummy.FieldName)
}

// Where appends a list predicates to the DummyMutation builder.
func (m *DummyMutation) Where(ps ...predicate.Dummy) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DummyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DummyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Dummy, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DummyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DummyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Dummy).
func (m *DummyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DummyMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, dummy.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dummy.FieldUpdatedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, dummy.FieldTenantID)
	}
	if m.created_by != nil {
		fields = append(fields, dummy.FieldCreatedBy)
	}
	if m.owned_by != nil {
		fields = append(fields, dummy.FieldOwnedBy)
	}
	if m.name != nil {
		fields = append(fields, dummy.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DummyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dummy.FieldCreatedAt:
		return m.CreatedAt()
	case dummy.FieldUpdatedAt:
		return m.UpdatedAt()
	case dummy.FieldTenantID:
		return m.TenantID()
	case dummy.FieldCreatedBy:
		return m.CreatedBy()
	case dummy.FieldOwnedBy:
		return m.OwnedBy()
	case dummy.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DummyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dummy.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dummy.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case dummy.FieldTenantID:
		return m.OldTenantID(ctx)
	case dummy.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case dummy.FieldOwnedBy:
		return m.OldOwnedBy(ctx)
	case dummy.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Dummy field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DummyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dummy.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dummy.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case dummy.FieldTenantID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case dummy.FieldCreatedBy:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case dummy.FieldOwnedBy:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnedBy(v)
		return nil
	case dummy.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Dummy field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DummyMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, dummy.FieldTenantID)
	}
	if m.addcreated_by != nil {
		fields = append(fields, dummy.FieldCreatedBy)
	}
	if m.addowned_by != nil {
		fields = append(fields, dummy.FieldOwnedBy)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DummyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dummy.FieldTenantID:
		return m.AddedTenantID()
	case dummy.FieldCreatedBy:
		return m.AddedCreatedBy()
	case dummy.FieldOwnedBy:
		return m.AddedOwnedBy()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DummyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dummy.FieldTenantID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case dummy.FieldCreatedBy:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedBy(v)
		return nil
	case dummy.FieldOwnedBy:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOwnedBy(v)
		return nil
	}
	return fmt.Errorf("unknown Dummy numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DummyMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dummy.FieldTenantID) {
		fields = append(fields, dummy.FieldTenantID)
	}
	if m.FieldCleared(dummy.FieldCreatedBy) {
		fields = append(fields, dummy.FieldCreatedBy)
	}
	if m.FieldCleared(dummy.FieldOwnedBy) {
		fields = append(fields, dummy.FieldOwnedBy)
	}
	if m.FieldCleared(dummy.FieldName) {
		fields = append(fields, dummy.FieldName)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DummyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DummyMutation) ClearField(name string) error {
	switch name {
	case dummy.FieldTenantID:
		m.ClearTenantID()
		return nil
	case dummy.FieldCreatedBy:
		m.ClearCreatedBy()
		return nil
	case dummy.FieldOwnedBy:
		m.ClearOwnedBy()
		return nil
	case dummy.FieldName:
		m.ClearName()
		return nil
	}
	return fmt.Errorf("unknown Dummy nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DummyMutation) ResetField(name string) error {
	switch name {
	case dummy.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dummy.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case dummy.FieldTenantID:
		m.ResetTenantID()
		return nil
	case dummy.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case dummy.FieldOwnedBy:
		m.ResetOwnedBy()
		return nil
	case dummy.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Dummy field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DummyMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DummyMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DummyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DummyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DummyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DummyMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DummyMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Dummy unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DummyMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Dummy edge %s", name)
}
