package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/saurabh/entgo-microservices/auth/internal/ent"
)

// CreateBrand is the resolver for the createBrand mutation.
func (r *mutationResolver) CreateBrand(ctx context.Context, input ent.CreateBrandInput) (*ent.Brand, error) {
	return r.Resolver.client.Brand.Create().SetInput(input).Save(ctx)
}

// CreateBulkBrand is the resolver for the createBulkBrand mutation.
func (r *mutationResolver) CreateBulkBrand(ctx context.Context, input []*ent.CreateBrandInput) ([]*ent.Brand, error) {
	builders := make([]*ent.BrandCreate, len(input))
	for i, inp := range input {
		builders[i] = r.Resolver.client.Brand.Create().SetInput(*inp)
	}
	return r.Resolver.client.Brand.CreateBulk(builders...).Save(ctx)
}

// UpdateBrand is the resolver for the updateBrand mutation.
func (r *mutationResolver) UpdateBrand(ctx context.Context, id int, input ent.UpdateBrandInput) (*ent.Brand, error) {
	return r.Resolver.client.Brand.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteBrand is the resolver for the deleteBrand mutation.
func (r *mutationResolver) DeleteBrand(ctx context.Context, id int) (bool, error) {
	err := r.Resolver.client.Brand.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return false, err
	}
	return true, nil
}

// BrandByID is the resolver for the BrandByID field.
func (r *queryResolver) BrandByID(ctx context.Context, id int) (*ent.Brand, error) {
	return r.Resolver.client.Brand.Get(ctx, id)
}

// Brands is the resolver for the Brands field.
func (r *queryResolver) Brands(ctx context.Context, first *int, after *entgql.Cursor[int], last *int, before *entgql.Cursor[int], orderBy *ent.BrandOrder, where *ent.BrandWhereInput) (*ent.BrandConnection, error) {
	return r.Resolver.client.Brand.Query().Paginate(ctx, after, first, before, last, ent.WithBrandFilter(where.Filter), ent.WithBrandOrder(orderBy))
}
