// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: user/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash    string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Phone           string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address         string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	UserType        string                 `protobuf:"bytes,8,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	UserCode        string                 `protobuf:"bytes,9,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	CompanyName     string                 `protobuf:"bytes,10,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CustomerType    string                 `protobuf:"bytes,11,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	PaymentTerms    int32                  `protobuf:"varint,12,opt,name=payment_terms,json=paymentTerms,proto3" json:"payment_terms,omitempty"`
	IsActive        bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,14,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	EmailVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=email_verified_at,json=emailVerifiedAt,proto3,oneof" json:"email_verified_at,omitempty"`
	LastLogin       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=last_login,json=lastLogin,proto3,oneof" json:"last_login,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *User) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *User) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *User) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *User) GetPaymentTerms() int32 {
	if x != nil {
		return x.PaymentTerms
	}
	return 0
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetEmailVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsRequest) Reset() {
	*x = GetUsersByIDsRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsRequest) ProtoMessage() {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersByIDsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsersByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsResponse) Reset() {
	*x = GetUsersByIDsResponse{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsResponse) ProtoMessage() {}

func (x *GetUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersByIDsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1b\n" +
	"\tuser_type\x18\b \x01(\tR\buserType\x12\x1b\n" +
	"\tuser_code\x18\t \x01(\tR\buserCode\x12!\n" +
	"\fcompany_name\x18\n" +
	" \x01(\tR\vcompanyName\x12#\n" +
	"\rcustomer_type\x18\v \x01(\tR\fcustomerType\x12#\n" +
	"\rpayment_terms\x18\f \x01(\x05R\fpaymentTerms\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x12%\n" +
	"\x0eemail_verified\x18\x0e \x01(\bR\remailVerified\x12K\n" +
	"\x11email_verified_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0femailVerifiedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"last_login\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tlastLogin\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x14\n" +
	"\x12_email_verified_atB\r\n" +
	"\v_last_login\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"8\n" +
	"\x13GetUserByIDResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"(\n" +
	"\x14GetUsersByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"<\n" +
	"\x15GetUsersByIDsResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserR\x05users2\xa7\x01\n" +
	"\vUserService\x12H\n" +
	"\vGetUserByID\x12\x1b.user.v1.GetUserByIDRequest\x1a\x1c.user.v1.GetUserByIDResponse\x12N\n" +
	"\rGetUsersByIDs\x12\x1d.user.v1.GetUsersByIDsRequest\x1a\x1e.user.v1.GetUsersByIDsResponseBAZ?github.com/saurabh/entgo-microservices/pkg/proto/user/v1;userv1b\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.v1.User
	(*GetUserByIDRequest)(nil),    // 1: user.v1.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),   // 2: user.v1.GetUserByIDResponse
	(*GetUsersByIDsRequest)(nil),  // 3: user.v1.GetUsersByIDsRequest
	(*GetUsersByIDsResponse)(nil), // 4: user.v1.GetUsersByIDsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_user_user_proto_depIdxs = []int32{
	5, // 0: user.v1.User.email_verified_at:type_name -> google.protobuf.Timestamp
	5, // 1: user.v1.User.last_login:type_name -> google.protobuf.Timestamp
	5, // 2: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: user.v1.GetUserByIDResponse.user:type_name -> user.v1.User
	0, // 5: user.v1.GetUsersByIDsResponse.users:type_name -> user.v1.User
	1, // 6: user.v1.UserService.GetUserByID:input_type -> user.v1.GetUserByIDRequest
	3, // 7: user.v1.UserService.GetUsersByIDs:input_type -> user.v1.GetUsersByIDsRequest
	2, // 8: user.v1.UserService.GetUserByID:output_type -> user.v1.GetUserByIDResponse
	4, // 9: user.v1.UserService.GetUsersByIDs:output_type -> user.v1.GetUsersByIDsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	file_user_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
