// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"github.com/saurabh/entgo-microservices/auth/ent/schema"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/brand"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/permission"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/role"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/rolepermission"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/tenant"
	"github.com/saurabh/entgo-microservices/auth/internal/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandMixin := schema.Brand{}.Mixin()
	brandHooks := schema.Brand{}.Hooks()
	brand.Hooks[0] = brandHooks[0]
	brand.Hooks[1] = brandHooks[1]
	brand.Hooks[2] = brandHooks[2]
	brand.Hooks[3] = brandHooks[3]
	brand.Hooks[4] = brandHooks[4]
	brandMixinFields0 := brandMixin[0].Fields()
	_ = brandMixinFields0
	brandMixinFields1 := brandMixin[1].Fields()
	_ = brandMixinFields1
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescCreatedAt is the schema descriptor for created_at field.
	brandDescCreatedAt := brandMixinFields0[1].Descriptor()
	// brand.DefaultCreatedAt holds the default value on creation for the created_at field.
	brand.DefaultCreatedAt = brandDescCreatedAt.Default.(func() time.Time)
	// brandDescUpdatedAt is the schema descriptor for updated_at field.
	brandDescUpdatedAt := brandMixinFields0[2].Descriptor()
	// brand.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	brand.DefaultUpdatedAt = brandDescUpdatedAt.Default.(func() time.Time)
	// brand.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	brand.UpdateDefaultUpdatedAt = brandDescUpdatedAt.UpdateDefault.(func() time.Time)
	// brandDescTenantID is the schema descriptor for tenant_id field.
	brandDescTenantID := brandMixinFields1[0].Descriptor()
	// brand.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	brand.TenantIDValidator = brandDescTenantID.Validators[0].(func(int) error)
	// brandDescName is the schema descriptor for name field.
	brandDescName := brandFields[0].Descriptor()
	// brand.NameValidator is a validator for the "name" field. It is called by the builders before save.
	brand.NameValidator = func() func(string) error {
		validators := brandDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// brandDescID is the schema descriptor for id field.
	brandDescID := brandMixinFields0[0].Descriptor()
	// brand.IDValidator is a validator for the "id" field. It is called by the builders before save.
	brand.IDValidator = brandDescID.Validators[0].(func(int) error)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionMixinFields1 := permissionMixin[1].Fields()
	_ = permissionMixinFields1
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields0[1].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields0[2].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescTenantID is the schema descriptor for tenant_id field.
	permissionDescTenantID := permissionMixinFields1[0].Descriptor()
	// permission.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	permission.TenantIDValidator = permissionDescTenantID.Validators[0].(func(int) error)
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[0].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDisplayName is the schema descriptor for display_name field.
	permissionDescDisplayName := permissionFields[1].Descriptor()
	// permission.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	permission.DisplayNameValidator = func() func(string) error {
		validators := permissionDescDisplayName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(display_name string) error {
			for _, fn := range fns {
				if err := fn(display_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[2].Descriptor()
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescResource is the schema descriptor for resource field.
	permissionDescResource := permissionFields[3].Descriptor()
	// permission.ResourceValidator is a validator for the "resource" field. It is called by the builders before save.
	permission.ResourceValidator = func() func(string) error {
		validators := permissionDescResource.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource string) error {
			for _, fn := range fns {
				if err := fn(resource); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescIsActive is the schema descriptor for is_active field.
	permissionDescIsActive := permissionFields[4].Descriptor()
	// permission.DefaultIsActive holds the default value on creation for the is_active field.
	permission.DefaultIsActive = permissionDescIsActive.Default.(bool)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionMixinFields0[0].Descriptor()
	// permission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	permission.IDValidator = permissionDescID.Validators[0].(func(int) error)
	roleMixin := schema.Role{}.Mixin()
	role.Policy = privacy.NewPolicies(schema.Role{})
	role.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := role.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	roleHooks := schema.Role{}.Hooks()

	role.Hooks[1] = roleHooks[0]

	role.Hooks[2] = roleHooks[1]

	role.Hooks[3] = roleHooks[2]

	role.Hooks[4] = roleHooks[3]

	role.Hooks[5] = roleHooks[4]
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescTenantID is the schema descriptor for tenant_id field.
	roleDescTenantID := roleMixinFields1[0].Descriptor()
	// role.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	role.TenantIDValidator = roleDescTenantID.Validators[0].(func(int) error)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDisplayName is the schema descriptor for display_name field.
	roleDescDisplayName := roleFields[1].Descriptor()
	// role.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	role.DisplayNameValidator = func() func(string) error {
		validators := roleDescDisplayName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(display_name string) error {
			for _, fn := range fns {
				if err := fn(display_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescIsActive is the schema descriptor for is_active field.
	roleDescIsActive := roleFields[3].Descriptor()
	// role.DefaultIsActive holds the default value on creation for the is_active field.
	role.DefaultIsActive = roleDescIsActive.Default.(bool)
	// roleDescPriority is the schema descriptor for priority field.
	roleDescPriority := roleFields[4].Descriptor()
	// role.DefaultPriority holds the default value on creation for the priority field.
	role.DefaultPriority = roleDescPriority.Default.(int)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(int) error)
	rolepermissionMixin := schema.RolePermission{}.Mixin()
	rolepermission.Policy = privacy.NewPolicies(schema.RolePermission{})
	rolepermission.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := rolepermission.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	rolepermissionHooks := schema.RolePermission{}.Hooks()

	rolepermission.Hooks[1] = rolepermissionHooks[0]

	rolepermission.Hooks[2] = rolepermissionHooks[1]

	rolepermission.Hooks[3] = rolepermissionHooks[2]

	rolepermission.Hooks[4] = rolepermissionHooks[3]

	rolepermission.Hooks[5] = rolepermissionHooks[4]
	rolepermissionMixinFields0 := rolepermissionMixin[0].Fields()
	_ = rolepermissionMixinFields0
	rolepermissionMixinFields1 := rolepermissionMixin[1].Fields()
	_ = rolepermissionMixinFields1
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionMixinFields0[1].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	// rolepermissionDescUpdatedAt is the schema descriptor for updated_at field.
	rolepermissionDescUpdatedAt := rolepermissionMixinFields0[2].Descriptor()
	// rolepermission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rolepermission.DefaultUpdatedAt = rolepermissionDescUpdatedAt.Default.(func() time.Time)
	// rolepermission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rolepermission.UpdateDefaultUpdatedAt = rolepermissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rolepermissionDescTenantID is the schema descriptor for tenant_id field.
	rolepermissionDescTenantID := rolepermissionMixinFields1[0].Descriptor()
	// rolepermission.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	rolepermission.TenantIDValidator = rolepermissionDescTenantID.Validators[0].(func(int) error)
	// rolepermissionDescCanRead is the schema descriptor for can_read field.
	rolepermissionDescCanRead := rolepermissionFields[0].Descriptor()
	// rolepermission.DefaultCanRead holds the default value on creation for the can_read field.
	rolepermission.DefaultCanRead = rolepermissionDescCanRead.Default.(bool)
	// rolepermissionDescCanCreate is the schema descriptor for can_create field.
	rolepermissionDescCanCreate := rolepermissionFields[1].Descriptor()
	// rolepermission.DefaultCanCreate holds the default value on creation for the can_create field.
	rolepermission.DefaultCanCreate = rolepermissionDescCanCreate.Default.(bool)
	// rolepermissionDescCanUpdate is the schema descriptor for can_update field.
	rolepermissionDescCanUpdate := rolepermissionFields[2].Descriptor()
	// rolepermission.DefaultCanUpdate holds the default value on creation for the can_update field.
	rolepermission.DefaultCanUpdate = rolepermissionDescCanUpdate.Default.(bool)
	// rolepermissionDescCanDelete is the schema descriptor for can_delete field.
	rolepermissionDescCanDelete := rolepermissionFields[3].Descriptor()
	// rolepermission.DefaultCanDelete holds the default value on creation for the can_delete field.
	rolepermission.DefaultCanDelete = rolepermissionDescCanDelete.Default.(bool)
	// rolepermissionDescID is the schema descriptor for id field.
	rolepermissionDescID := rolepermissionMixinFields0[0].Descriptor()
	// rolepermission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	rolepermission.IDValidator = rolepermissionDescID.Validators[0].(func(int) error)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields0[2].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[0].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[1].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = func() func(string) error {
		validators := tenantDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescDomain is the schema descriptor for domain field.
	tenantDescDomain := tenantFields[2].Descriptor()
	// tenant.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	tenant.DomainValidator = tenantDescDomain.Validators[0].(func(string) error)
	// tenantDescIsActive is the schema descriptor for is_active field.
	tenantDescIsActive := tenantFields[8].Descriptor()
	// tenant.DefaultIsActive holds the default value on creation for the is_active field.
	tenant.DefaultIsActive = tenantDescIsActive.Default.(bool)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tenant.IDValidator = tenantDescID.Validators[0].(func(int) error)
	userMixin := schema.User{}.Mixin()
	user.Policy = privacy.NewPolicies(schema.User{})
	user.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := user.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	userHooks := schema.User{}.Hooks()

	user.Hooks[1] = userHooks[0]

	user.Hooks[2] = userHooks[1]

	user.Hooks[3] = userHooks[2]

	user.Hooks[4] = userHooks[3]

	user.Hooks[5] = userHooks[4]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userMixinFields1[0].Descriptor()
	// user.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	user.TenantIDValidator = userDescTenantID.Validators[0].(func(int) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[4].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[6].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(string)
	// user.UserTypeValidator is a validator for the "user_type" field. It is called by the builders before save.
	user.UserTypeValidator = userDescUserType.Validators[0].(func(string) error)
	// userDescUserCode is the schema descriptor for user_code field.
	userDescUserCode := userFields[7].Descriptor()
	// user.UserCodeValidator is a validator for the "user_code" field. It is called by the builders before save.
	user.UserCodeValidator = userDescUserCode.Validators[0].(func(string) error)
	// userDescCompanyName is the schema descriptor for company_name field.
	userDescCompanyName := userFields[8].Descriptor()
	// user.CompanyNameValidator is a validator for the "company_name" field. It is called by the builders before save.
	user.CompanyNameValidator = userDescCompanyName.Validators[0].(func(string) error)
	// userDescCustomerType is the schema descriptor for customer_type field.
	userDescCustomerType := userFields[9].Descriptor()
	// user.CustomerTypeValidator is a validator for the "customer_type" field. It is called by the builders before save.
	user.CustomerTypeValidator = userDescCustomerType.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[11].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[12].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
